name: Python Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test_ec2_stop_lambda:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        cd lambda_functions/ec2_simple/stop
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV

    - name: Run tests
      run: pytest lambda_functions/ec2_simple/stop/tests/test_main.py
